# Generated by Django 2.1.15 on 2022-01-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='exams',
            field=models.ManyToManyField(blank=True, null=True, to='core.Examination'),
        ),
    ]
