# Generated by Django 2.1.15 on 2022-01-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220123_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('ects', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(related_name='courses', to='core.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='progress',
            name='degree',
        ),
        migrations.AddField(
            model_name='progress',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='transcript',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Transcript'),
        ),
    ]
