# Generated by Django 2.1.15 on 2022-01-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_progress_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='exams',
            field=models.ManyToManyField(related_name='progress', to='core.Examination'),
        ),
    ]
