# Generated by Django 2.1.15 on 2022-01-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220123_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='course',
            new_name='courses',
        ),
    ]
