# Generated by Django 2.1.15 on 2022-01-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220126_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='progress', to='core.Examination'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='grade_courses',
            field=models.ManyToManyField(blank=True, related_name='grade_courses', to='core.CourseGrade'),
        ),
    ]
