# Generated by Django 2.1.15 on 2022-01-26 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220126_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ects',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='grade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
