# Generated by Django 2.1.15 on 2022-01-23 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transcript_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField()),
                ('courses', models.ManyToManyField(related_name='courses', to='core.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='courses',
        ),
        migrations.AddField(
            model_name='transcript',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='semesters',
            field=models.ManyToManyField(related_name='semesters', to='core.Semester'),
        ),
    ]
