# Generated by Django 2.1.15 on 2022-01-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220123_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='course',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='user',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='semesters',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='transcript',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
