# Generated by Django 2.1.15 on 2022-01-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220123_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
