# Generated by Django 2.1.15 on 2022-01-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220123_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='grade_courses',
            field=models.ManyToManyField(related_name='grade_courses', to='core.CourseGrade'),
        ),
    ]
